### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by marissa999** [fmsouza/wcode#10]
I guess I can't use HTTPS? The frontend gives me several errors when I try to load wcode via https. It would be nice to be able to code remotly on my server like I do with codiad.

There are no errors on my server (besides xdg open cant find any browser), but there are some errors that appears in the js console on chrome:

index.js:6 Mixed Content: The page at 'https://dev.foo.moe/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://dev.foo.moe/'. This request has been blocked; this endpoint must be available over WSS.
(anonymous) @ index.js:6
(anonymous) @ setup.js:11
(anonymous) @ index.js:14

index.js:6 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at https://dev.foo.moe/app/bundle.js:1:270724
    at https://dev.foo.moe/app/bundle.js:1:270861
    at https://dev.foo.moe/app/bundle.js:1:270999
(anonymous) @ index.js:6
(anonymous) @ setup.js:11
(anonymous) @ index.js:14

registerServiceWorker.js:71 Error during service worker registration: TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.

Maybe try to add a boolean for https? idk ._. Sorry

**Comment by fmsouza** [comment]
Hi @LittleSatan, initially this project was concepted to run locally, so the connection is hardcoded to use the WebSocket protocol without SSL, and also to always try to open the browser in the sequence.

It can be changed to accept WSS connections too, but unfortunately I'm not very used to this kind of configuration. As far as I know, you'll need to be able to provide your keys so the server can start with SSL encryption. Is it right?

**Comment by fmsouza** [comment]
@LittleSatan Just implemented an attempt to allow SSL encryption on the server, could you please try and tell me if it fixes your problem?

The changes are in the [https](https://github.com/fmsouza/wcode/tree/https) branch. You can try by doing the following:

```bash
$ git clone -b https https://github.com/fmsouza/wcode.git
$ cd wcode && npm install
$ npm run build
$ ./wcode --ssl path/to/your/keys path/to/your/project
```

**Comment by marissa999** [comment]
Hm. Doesn't seem to work? I've build it from the branch and copied and renamed my certs but I only get a 502 bad gateway error? My first guess is that there is something wrong with my certs? But I can't even imagine where the error could be?

Funny with the ssl branch I can see a bit more of the interface without the --ssl option. But I still cant modify anything and I get lots of different errors. But this was to be expected ig.

(sadly I also dont have that much time to test stuff. Im on vacation rn .-.)

**Comment by fmsouza** [comment]
Sorry, last night I've implemented this on the rush, so I didn't took care of every details. I just tested it further are fixed some stuff and it is fully working with the SSL certificate and key right now. Notica that you must have 2 files in the path you'll provide with the `--ssl` option: `certificate.pem` and `key.pem`. If it does not work now, probably you are having problems with your key.
