### ISSUE TITLE
Question - Project Vision / Roadmap

### ISSUE THREAD

**Issue by evra** [fmsouza/wcode#21]
Hello,

Do you have concrete plans for future development of the project? May be a roadmap or so. 
It would be great having some additional features such as "Problems View", "Command Pallet", Plugins, LSP integration for other languages and other features.

Thanks.

**Comment by fmsouza** [comment]
Hello @evra!

Unfortunately right now I don't. It begun as a side-project, as a hobby, to resolve a particular need I had by the time. Right now I have no time to keep on working on these projects (I'm working on having this time again, I miss it a lot), so it's mostly stopped.

But as it's open-source, it would evolve much faster if there was a more engaged community around it, but it never had. So this project completely relies on me as of now.

If you are interested in seeing this project making it further, you could raise issues with `Feature Requests` and also send PRs with the implementations.
