### ISSUE TITLE
events.js:170 error

### ISSUE THREAD

**Issue by maoamid** [fmsouza/wcode#22]
wcode cannot serve, crash after the server start:
`events.js:170
throw er; //Unhandled 'error' event`

Error: spawn xdg-open ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
[...]

**Comment by IanusInferus** [comment]
I have encountered this on Windows and WSL and have found a workaround. I think you can add '--headless' argument to prevent it from trying to open a window.

**Comment by maoamid** [comment]
the problem cannot be reproduced after last dependencies updates.
